# Generated by Django 4.2.6 on 2023-10-24 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=5000)),
                ('image', models.ImageField(upload_to='recipes_images')),
                ('type', models.CharField(choices=[('first', 'первое'), ('second', 'второе'), ('dessert', 'десерт')], max_length=30)),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
