# Generated by Django 4.2.6 on 2023-10-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_alter_recipe_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='private_choise',
            field=models.CharField(choices=[('PR', 'Загрузить приватно'), ('PB', 'Опубликовать для всех')], default='PB', max_length=2),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes_images'),
        ),
    ]
