# Generated by Django 4.2.6 on 2023-10-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_recipe_private_choise_alter_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='public',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='private_choise',
            field=models.CharField(choices=[('PR', 'Загрузить приватно'), ('PB', 'Добавить в Книгу рецептов')], default='PB', max_length=2),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('Первое', 'первое'), ('Второе', 'второе'), ('Салат', 'салат'), ('Десерт', 'десерт'), ('Прочее', 'прочее')], max_length=30),
        ),
    ]
