# Generated by Django 4.2.6 on 2023-11-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_remove_recipe_public_alter_recipe_private_choise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(blank=True, choices=[('Первое', 'первое'), ('Второе', 'второе'), ('Салат', 'салат'), ('Десерт', 'десерт'), ('Прочее', 'прочее')], max_length=30),
        ),
    ]
