# Generated by Django 4.2.6 on 2023-11-01 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0006_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={},
        ),
    ]
