# Generated by Django 4.2.6 on 2023-11-01 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0007_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['published_date']},
        ),
    ]
